{
 "title": "GNSS - BRIN - Latest",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gnss_id",
    "label": "GNSS ID",
    "query": "SELECT DISTINCT gnss_id FROM gnss ORDER BY gnss_id\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Position",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  g1.timestamp,\r\n  (\r\n    FLOOR(substring(g1.value from '([0-9]+\\.[0-9]+)')::numeric / 100) + \r\n    ((substring(g1.value from '([0-9]+\\.[0-9]+)')::numeric - (FLOOR(substring(g1.value from '([0-9]+\\.[0-9]+)')::numeric / 100) * 100)) / 60)\r\n  ) * -1 AS latitude, \r\n\r\n  (\r\n    FLOOR(substring(g2.value from '([0-9]+\\.[0-9]+)')::numeric / 100) + \r\n    ((substring(g2.value from '([0-9]+\\.[0-9]+)')::numeric - (FLOOR(substring(g2.value from '([0-9]+\\.[0-9]+)')::numeric / 100) * 100)) / 60)\r\n  ) AS longitude\r\nFROM gnss g1\r\nJOIN gnss g2 \r\n  ON g1.timestamp = g2.timestamp \r\n  AND g1.gnss_id = g2.gnss_id\r\nWHERE g1.sensor_id LIKE 'LAT%'  \r\n  AND g2.sensor_id LIKE 'LON%' \r\n  AND g1.value ~ '[0-9]+\\.[0-9]+'\r\n  AND g2.value ~ '[0-9]+\\.[0-9]+'\r\n  AND g1.gnss_id = '$gnss_id'  \r\n  AND g1.value IS NOT NULL\r\n  AND g1.value <> ''\r\n  AND g2.value IS NOT NULL\r\n  AND g2.value <> ''\r\n  AND $__timeFilter(g1.timestamp)\r\n  ORDER BY g1.timestamp DESC\r\nLIMIT 1000;  \r\n"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\r\n    FLOOR(substring(value from '([0-9]+\\.[0-9]+)')::numeric / 100) + \r\n    ((substring(value from '([0-9]+\\.[0-9]+)')::numeric - (FLOOR(substring(value from '([0-9]+\\.[0-9]+)')::numeric / 100) * 100)) / 60)\r\n  ) as longitude,\r\n  gnss_id, \r\n  sensor_id, \r\n  timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'LON%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n   AND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\r\n    FLOOR(substring(value from '([0-9]+\\.[0-9]+)')::numeric / 100) + \r\n    ((substring(value from '([0-9]+\\.[0-9]+)')::numeric - (FLOOR(substring(value from '([0-9]+\\.[0-9]+)')::numeric / 100) * 100)) / 60)\r\n  ) * -1 AS latitude, \r\n  gnss_id, \r\n  sensor_id, \r\n  timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'LAT%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  "
    }
   ]
  },
  {
   "title": "Debug",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT gnss_id, timestamp, CAST(value AS DOUBLE PRECISION) as \"value\", sensor_id\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'    \r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp DESC LIMIT 1000\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Longitude Direction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'LOD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Latitude Direction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'LAD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Satellite Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SAT%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Total Satelite for Position Lock",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SCO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Geodial Sepatial",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'GSE%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Signal Noise Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SNR%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SPD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Heading",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HAD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'ALT%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Position Delution of Precisison",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'PDO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Horizontal Delution of Precisison",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HDO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Vertical Delution of Precisison",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, timestamp,sensor_id\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'VDO%'\r\n  AND value ~ '^[0-9\\.]+$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  "
    }
   ]
  },
  {
   "title": "Magnetic Variation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'MVA%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Magnetic Value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'MVR%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'TEM%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'TEM%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HUM%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\nAND value IS NOT NULL\r\n  AND value <> ''\r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp DESC\r\nLIMIT 5;\r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HUM%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Total Satelite for Position Lock",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SCO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Satellite Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SAT%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Geodial Sepatial",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'GSE%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Signal Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SNR%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'SPD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Heading (degree)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HAD%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Position Delution of Precisison",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'PDO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Horizontal Delution of Precisison",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'HDO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Vertical Delution of Precisison",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'VDO%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Magnetic Variation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT CAST(value AS DOUBLE PRECISION) as \"value\", gnss_id, sensor_id, timestamp\r\nFROM gnss\r\nWHERE gnss_id = '$gnss_id'\r\n  AND sensor_id LIKE 'MVA%'\r\n  AND value ~ '^[0-9]+(\\.[0-9]+)?$'  \r\n  AND $__timeFilter(timestamp)\r\n  ORDER BY timestamp \r\n  \r\n  "
    }
   ]
  }
 ]
}